#! /bin/bash

# Simple CAOS command line for use with Docking Station
# or Creatures 3 running under Linux.  It lets you inject
# commands in the game scripting language into a running
# world.

# To learn more about CAOS, see http://cdn.creatures.net

# Requires installation of netcat (nc) first.  Your
# distribution should have a package for it, or it is very
# easy to compile from source.

NORMAL="[0m"
PREVIOUS="help"
HISTORY_FILE="caos_history.txt"

function cleanup()
{
	# Turn off yellow text
	echo -n "${NORMAL}"
}
trap cleanup EXIT

cat <<END
CAOS Command Line
Warning! You can damage your world with this utility.
Return executes the last command again. Up / down navigate history.
Press Ctrl+C to exit.
END

truncate -s 1M ${HISTORY_FILE}
history -r ${HISTORY_FILE}

while [ 1 = 1 ]
do
	# TODO: Also, you can only enter single lines.  The way
	# injection works in Linux, you need multiple lines to enter
	# scripts (without an error from rscr not being understood).
	read -e -p "CAOS> [1;33m" INPUT
    history -s "${INPUT}"
	echo -n "${NORMAL}"
	[ -z "${INPUT}" ] && INPUT=${PREVIOUS}
	# We send the input to the appropriate local port, followed
	# by the text "rscr".  The text "rscr" completes the CAOS
	# telling the engine to execute what it has up to then, and
	# close the socket.
	nc localhost `cat ~/.creaturesengine/port` <<END
${INPUT}

rscr
END
    history -w ${HISTORY_FILE}
	echo
	PREVIOUS=${INPUT}
done


