@echo off


REG DELETE "HKEY_CURRENT_USER\Software\Gameware Development" /F
REG DELETE "HKEY_CLASSES_ROOT\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\Gameware Development" /F
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\CyberLife Technology" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\CyberLife Technology" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Creature Labs" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Gameware Development" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\Creatures Exodus" /F
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\Creatures Exodus" /F
REG DELETE "HKEY_CLASSES_ROOT\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\CyberLife Technology" /F
REG DELETE "HKEY_CURRENT_USER\Software\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\CyberLife Technology" /F

Rem REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com" /F

exit
